[package]
name = "stateflow"
version = "0.2.1"
edition = "2024"


[dependencies]
chrono = { version = "0.4.41" }
thiserror = "2.0.12"

[dev-dependencies]
tokio = { version = "1.46.1", features = ["full"] }
