[package]
name = "stateflow"
version = "0.1.0"
edition = "2024"

[features]
chrono = ["dep:chrono"]
default = ["chrono"]

[dependencies]
thiserror = "2.0.12"
chrono = { version = "0.4.41", optional = true }

[dev-dependencies]
tokio = { version = "1.46.1", features = ["full"] }
